### ISSUE TITLE
Find existing Japanese NMT papers

### ISSUE THREAD

**Issue by dennybritz** [rpryzant/japanese_corpus#1]
To compare our datasets and final BLEU score results to what has been published we should do some research and figure out what people have been doning. What datasets are researchers using? What is their train/dev/test set? What kind of scores do they get? Let's collect a list of papers and results.

**Comment by rpryzant** [comment]
**Learning to Parse and Translate Improves Neural Machine Translation (https://arxiv.org/pdf/1702.03525.pdf)**
* corpus: [ASPEC](http://lotus.kuee.kyoto-u.ac.jp/ASPEC/) - 3M sentences from translated scientific abstracts.
* train/dev/test: 100K pairs with length < 50 / `dev.txt` from corpus (1.7K) / `test.txt` from corpus (1.8K)
* Baseline: 17.88 BLEU, 71.27 RIBES
* Proposed: 18.84 BLEU, 72.25 RIBES

**Comment by rpryzant** [comment]
**Tree-to-Sequence Attentional Neural Machine Translation (https://arxiv.org/pdf/1603.06075.pdf)**
* **corpus**: [ASPEC](http://lotus.kuee.kyoto-u.ac.jp/ASPEC/)
* **train/dev/test**: first 1.5M pairs **/** provided dev (1.7k) **/** provided test (1.8k)
* **baseline [[1]](http://www.aclweb.org/anthology/W/W15/W15-5007.pdf):** 32.18 BLEU / 79.70 RIBES
* **proposed**: 34.36 BLEU / 81.46 RIBES

**Comment by rpryzant** [comment]
**Evaluating Neural Machine Translation in English-Japanese Task** (http://www.aclweb.org/anthology/W/W15/W15-5007.pdf)

**NOTE:** This one is really good, kind of a search space odyssey for EN-JP NMT. Great details on the tweaks it takes to get something working well.

* **corpus:** [ASPEC](http://lotus.kuee.kyoto-u.ac.jp/ASPEC/)
* **train/dev/test**: first 1.5M pairs, length filtered below 40, ended up with 1.1M pairs **/** provided dev **/** provided test
* **results:** 32.19 BLEU / 77.9 RIBES
* **note:** translated OOV words with unk_i, where i is the index of that word's source-side alignment. **IDEA**: use attention for this, annotate i as argmax over attentional hidden state scores.

**Comment by rpryzant** [comment]
**Japanese-English Machine Translation of Recipe Texts (http://www.aclweb.org/anthology/W/W16/W16-46.pdf#page=72)**

* **corpus**: 270K sentences coming from parallel recipes 
* **train/dev/test**: 1.7k randomly chosen for dev **/** 1.6k random test **/** remainder train
* **results**: 25.68 BLEU / 77.84 RIBES

**Comment by rpryzant** [comment]
**[Controlling the Voice of a Sentence in Japanese-to-English Neural
Machine Translation](http://www.aclweb.org/anthology/W/W16/W16-46.pdf#page=217)**

* **corpus**: ASPEC (provided dev/test)
* **results**: 18.29

**Comment by rpryzant** [comment]
**[Google’s Multilingual Neural Machine Translation System: Enabling Zero-Shot Translation](https://arxiv.org/pdf/1611.04558.pdf)**

* **corpus**: internal EN-JA corpus that's "two to three orders of magnitude larger" than WMT (e..g 50-500M sentences) (WOW)
*  **results**: 23.41 BLEU

**Comment by rpryzant** [comment]
[Residual Stacking of RNNs for Neural Machine Translation](http://www.aclweb.org/anthology/W/W16/W16-46.pdf#page=237)

* **corpus**: ASPEC (tokenized japanese on the **per-character level**
* 200k vocab size for english, "no limit" for japanese(?)
* **results**: baseline: 29.32 BLEU / 79.49 RIBES. Proposed: 30.75 BLEU / 79.88 RIBES
