### ISSUE TITLE
Domain Adaptation ASPEC <> Subs

### ISSUE THREAD

**Issue by dennybritz** [rpryzant/japanese_corpus#11]
Running experiments for domain adaptation from subtitles to ASPEC:

### 1\. ASPEC baseline performance

See https://github.com/rpryzant/japanese_corpus/issues/9

```
BLEU = 36.11, 66.9/43.8/30.5/21.9 (BP=0.965, ratio=0.965, hyp_len=51946, ref_len=53809)
```

### 2\. Train on combined ASPEC and Subtitles data

Hypothesis is that this will lower (or not change) the BLEU score because the domains are so different. Running experiment now.

Exact preprocessing: https://gist.github.com/dennybritz/8a42683c4668041f77ccc7e615a513e2

### 3\. Implementation domain adaptation model.

Ideas:

1. Add a discriminator to distinguish between domains
2. Add a domain confusion loss, e.g. https://arxiv.org/abs/1412.3474, https://arxiv.org/abs/1505.07818
3. Train two models and share weights

**Comment by rpryzant** [comment]
How is this going? Need someone to bounce ideas off of?

**Comment by dennybritz** [comment]
I'm running the experiments for the baselines and target tokens (should be converged soon). I should be able to finish the discriminator implementation today. I'll also re-run on the new data.

If you can do a literature review (there are a bunch of references in the doc) and maybe come up with more ideas of course that'd be great!

**Comment by rpryzant** [comment]
Great, take your time and good luck! 

Not very familiar with domain adaptation myself but I'll certainly look at those papers. I also have a meeting with my advisor tomorrow and can see what he has to say about the problem.
