### ISSUE TITLE
Find new dataset pair

### ISSUE THREAD

**Issue by rpryzant** [rpryzant/japanese_corpus#12]
It would strengthen our results if we showed the technique generalized across languages. Let's find another pair of datasets to play with.

**Comment by rpryzant** [comment]
**Places to look:**

* http://www.statmt.org/wmt13/translation-task.html
* http://lotus.kuee.kyoto-u.ac.jp/WAT/#task.html
* http://www.statmt.org/wmt17/translation-task.html

**Comment by rpryzant** [comment]
**Found something that might work: Chinese <=> English**

* **μtopia**: parallel corpus harvested from the Chinese equivalent of twitter.   
  * They provide a means to crawl 800k sentences, but only give 8k sentences directly
  * http://www.cs.cmu.edu/~lingwang/microtopia/
  * http://www.cs.cmu.edu/~lingwang/papers/acl2013.pdf
  * the 8k is at http://www.cs.cmu.edu/~lingwang/microtopia/#translation
* **UN corpus**: aligned proceedings from the UN
  * https://conferences.unite.un.org/UNCorpus/#introduction
  * not sure how large this dataset is, but what about taking an 8k subset of it to match the twitter data?

@dennybritz what do you think of this pair? I feel like twitter and UN data are going to be pretty different. If you like it I'll start preparing them for you.

**Comment by dennybritz** [comment]
Hmm, 8k sentences is very little. I think this is good only if you can somehow get the 800k. Is there nothing that is already ready to download at http://www.statmt.org/wmt17/translation-task.html and sufficiently different?

**Comment by rpryzant** [comment]
Hmm I don't think I have time to write another good crawler/aligner. 

The people over at utopia were able to get 14.33 BLEU on the 8k dataset ([link](http://www.cs.cmu.edu/~lingwang/microtopia/#translation) ). Is that too low to work with?

If it is too low, I'll look around some more. There's lots of parallel datasets but I don't know if any are distant enough for us to get any good results on. How many experiments can you run at once? Maybe we can try a few different dataset pairs and write about the ones that worked best...

**Comment by dennybritz** [comment]
Yeah, better to use the aligned data (http://www.statmt.org/wmt17/translation-task.html). I can definitely run them in parallel if we have them in the right format. I can try on the 8k data, but I'm not sure how strong of a point that would be for paper because it's a very unknown dataset.

**Comment by rpryzant** [comment]
**Some en-zh datasets**

* https://drive.google.com/open?id=0B6v0SLeq81aNZ2F4b3JiaGpsbmM

Note:
* The UN corpus was *huge* (~15M examples), so I took at 2M subset of it
* I was able to get ~10k examples for the twitter stuff. Not a lot, but my feeling is that this domain is the most different from the others.

**Comment by dennybritz** [comment]
Thanks for preparing! I think for our method to be effective both domains need to be of approximately the same size though. If one is much larger it will just dominate. You could downsample UN to 100k examples and upsample Twitter to 100k. Having a smaller data set would also be better in terms of training time. Also, could you generate combined wordpieces/data like I did inhttps://gist.github.com/dennybritz/8a42683c4668041f77ccc7e615a513e2#file-subtitles_aspec-sh? Sorry, I know it's a lot of work :/

Also, here's another idea for dataset(s):
- Domain 1: TED Corpus talks from IWSLT: http://alt.qcri.org/resources/qedcorpus/ - These are around 100-200k I think.
- Domain 2: Some news corpus form WLT.

I think having another more standard (DE, FR, etc) language pair may be good.

**Comment by rpryzant** [comment]
Oops! Sorry about that. Thought you needed shared bpe between languages, not between corpora. 

I agree about that. 10k is just too small. I'll prepare a couple corpus pairs and we can see how the chips fall.

Agreed w/r/t another language as well. I'll get that together also.

**Comment by rpryzant** [comment]
**en-zh and en-fr datasets**

* https://drive.google.com/open?id=0B6v0SLeq81aNNGkyQ3N0UTQyQVE

I included a bunch of corpus pairs, pick whichever you think would be best. 6.2G when unpacked.

All datasets are approximately 200k example (give or take a little)


en-zh datasets:
  - news: "News Commentary v12" from http://www.statmt.org/wmt17/translation-task.html
  - opensubtitles: http://opus.lingfil.uu.se/OpenSubtitles2016.php
  - un: https://conferences.unite.un.org/UNCorpus
  - ted: http://opus.lingfil.uu.se/TED2013.php
  - utopia: www.cs.cmu.edu/~lingwang/microtopia/

en-fr datasets:
   - europarl: "Europarl v7" from http://www.statmt.org/wmt17/translation-task.html
   - opensubtitles: http://opus.lingfil.uu.se/OpenSubtitles2016.php
   - un: https://conferences.unite.un.org/UNCorpus
   - ted: http://opus.lingfil.uu.se/TED2013.php
