### ISSUE TITLE
Merge with "traditional" data

### ISSUE THREAD

**Issue by dennybritz** [rpryzant/japanese_corpus#4]
For the final dataset we should also be using the already freely available datasets at http://www.phontron.com/japanese-translation-data.php?lang=en. More data is always good. Ideally we can bring all of these into the same format and finally merge them into a single dataset (but also keep them separate so that we can pick&choose).

**Comment by rpryzant** [comment]
If we take the top 1.5M from ASPEC and NTCIR, along with KFTT, we'll have doubled the size of the corpus.

**Comment by rpryzant** [comment]
100k subset of ASPEC is tokenized and split into train/test/val here: https://github.com/rpryzant/nmt/tree/master/phase_3_learning/datasets/aspec

**Comment by rpryzant** [comment]
**ASPEC preprocessed**
* https://drive.google.com/open?id=0B_bZck-ksdkpYTkzYUI1cDJOanM

**Subtitles 1.6M subset preprocessed**
* https://drive.google.com/file/d/0B6v0SLeq81aNeG85TWs5RmszcUk/view?usp=sharing

**Comment by rpryzant** [comment]
Subtitles 500k best-scoring:

* https://drive.google.com/file/d/0B6v0SLeq81aNSUttMWhNUndfM1k/view?usp=sharing

**Comment by rpryzant** [comment]
**Complete corpus V2**
* Shuffled
* ~3.25M examples
* https://drive.google.com/file/d/0B6v0SLeq81aNYVJiSHVXaTY2VVk/view?usp=sharing

**Comment by dennybritz** [comment]
Amazing :D

**Comment by rpryzant** [comment]
Yeah I used the matchings you gave me a while back. I cleaned them, filtered by length ratios, and removed dups before adding to the big corpus. Wish these subs were harvested consistently from each source. But I agree with you, improving the corpus is low priority at this point.
