### ISSUE TITLE
Create train/dev/test splits

### ISSUE THREAD

**Issue by dennybritz** [rpryzant/japanese_corpus#5]
Blocked by #1  and #4. To train a translation model we need to create proper train/dev/test splits. If there already exists a "standard"  test set we should probably use it.

**Comment by rpryzant** [comment]
I've been using this script to generate my splits:
https://github.com/rpryzant/nmt/blob/master/phase_3_learning/data/generate_splits.py


It gets all the indices of sentences less than a specified max length, then randomly draws train/dev/splits from that list.

**Comment by rpryzant** [comment]
Closing this as a dup of https://github.com/rpryzant/japanese_corpus/issues/4

Because once we finalize the corpus, making splits should be a an afterthought
