### ISSUE TITLE
Better alignment for subtitle files

### ISSUE THREAD

**Issue by dennybritz** [rpryzant/japanese_corpus#6]
Input: Two (English and Japanese) subtitle files that correspond to the same movie.
Output: A list of aligned sentences

Challenges:
- Subs may correspond to different movie versions and timestamps may be shifted by a few seconds/minutes
- Subs have different numbers of entries due to things like "Translated By"
- A single long sentence may be broken up in more than one subtitle event, but broken up different in English/Japanese due to the sentence structure being different. 

Ideas:
- Train something like [fast_align](https://github.com/clab/fast_align) on clean subs and use it to estimate sentence alignment.  This may require a tokenizer for Japanese, e.g. [mecab](http://taku910.github.io/mecab/)
- Do some kind of bi-partite graph matching (Review Stanford Mining Massive Datasets class?)
- Use length ratios

**Comment by rpryzant** [comment]
[This paper](https://pdfs.semanticscholar.org/e7e8/9205652c87a559f66f9126827a47366591c5.pdf) mentions a JP/EN sentence aligner that was used in the two biggest parallel corpora (ASPEC + PPC). I checked out the [page they mentioned](www2.nict.go.jp/astrec-att/member/mutiyama/software.html) but couldn't find anything. Have emailed the authors and will update with their software upon response.

**Comment by rpryzant** [comment]
I've finished the ratio thresholder and a fun little spellchecker (if we want to use that). 

I've started storing these aligners/cleaners in https://github.com/rpryzant/japanese_corpus/tree/master/alignment_cleaners

**Comment by dennybritz** [comment]
Check out https://arxiv.org/abs/1606.09560

**Comment by rpryzant** [comment]
Update: aligning and scoring matches based on **overlaps** instead of **exact matching** seems to work better

**Comment by dennybritz** [comment]
Sounds great. How exactly are you doing the matching now? Are you using something similar to what I tried for daddicts (vector similarities)?

**Comment by rpryzant** [comment]
There's two types of alignment now

* **file alignment**, which matches up japanese and english `.srt` files. I tried the vector similarity thing but couldn't get it to work very well...I think bucketing sub timestamps was problematic. Right now I'm ranking en `srt`'s by "% coverage" (= the % of the ja target's captions that are overlapped) and taking the top K matches
* **caption alignment**, which harvests en/ja subs from matched `.srt`'s. I gather all overlapping captions, rank by alignment length, then take the top N

Still need to do all the filtering/cleaning/spellchecking/etc, but what I have so far is in [this notebook](https://github.com/rpryzant/japanese_corpus/blob/master/parsers/subscene/v2/sub_parser.ipynb). The crawler won't be finished for another couple days but I've uploaded some sample data [here](https://github.com/rpryzant/japanese_corpus/tree/master/parsers/subscene/v2/out)

**Comment by rpryzant** [comment]
Closing this. 

Content words + TF-IDF cosine similarity seems to work very well.
