### ISSUE TITLE
Aquire ASPEC dataset

### ISSUE THREAD

**Issue by rpryzant** [rpryzant/japanese_corpus#8]
As per https://github.com/rpryzant/japanese_corpus/issues/1, it seems that most JA-EN NMT systems are trained & tested on the ASPEC corpus [[PDF]](http://www.lrec-conf.org/proceedings/lrec2016/pdf/621_Paper.pdf). 

We should get our hands on this dataset both for comparative evaluation and testing out ideas.

**Comment by rpryzant** [comment]
As of 3/6/17 I've put in a request for the corpus. No response yet.

**Comment by dennybritz** [comment]
Thanks for handling it, hopefully we can get our hands on it soon!

**Comment by rpryzant** [comment]
Boom! https://drive.google.com/file/d/0B6v0SLeq81aNRFhYTlE5Qy00R0E/view?usp=sharing

**Comment by dennybritz** [comment]
Awesome, that was fast! I'm in the middle of refactoring a bunch of stuff, but I'll try to run some baseline towards end of the week.

**Comment by khanhptnk** [comment]
hi can I ask whether you have to mail the license agreement to the ASPEC people or just emailing is enough. i'd greatly appreciate it

**Comment by rpryzant** [comment]
We emailed the agreement to `aspec@jst.go.jp` and they responded shortly afterwards
